database:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://192.168.31.45:3306/test?useSSL=false
#  url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false

#  username: root
#  password: 123123
  username: root
  password: root_password

mappers:
  - mapper/UserMapper.xml
  - mapper/QuoteMapper.xml
